// <auto-generated />
using System;
using BangNews.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BangNews.Api.Migrations
{
    [DbContext(typeof(BangNewsApiContext))]
    [Migration("20190702173946_Inicio")]
    partial class Inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BangNews.Api.Models.Autor", b =>
                {
                    b.Property<int>("AutorID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apelido")
                        .HasColumnName("Apelido")
                        .HasMaxLength(50);

                    b.Property<string>("Nome")
                        .HasColumnName("Nome")
                        .HasMaxLength(50);

                    b.HasKey("AutorID");

                    b.ToTable("Autor");
                });

            modelBuilder.Entity("BangNews.Api.Models.Nome", b =>
                {
                    b.Property<int>("NomeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nomes");

                    b.HasKey("NomeID");

                    b.ToTable("Nomes");
                });

            modelBuilder.Entity("BangNews.Api.Models.Noticia", b =>
                {
                    b.Property<int>("NoticiaID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AutorID")
                        .HasColumnName("AutorID")
                        .HasColumnType("int");

                    b.Property<string>("Conteudo")
                        .HasColumnName("Conteudo")
                        .HasMaxLength(2147483647);

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnName("DataCadastro")
                        .HasColumnType("Datetime");

                    b.Property<string>("Descricao")
                        .HasColumnName("Descricao")
                        .HasMaxLength(100);

                    b.Property<string>("Titulo")
                        .HasColumnName("Titulo")
                        .HasMaxLength(50);

                    b.HasKey("NoticiaID");

                    b.HasIndex("AutorID");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("BangNews.Api.Models.Noticia", b =>
                {
                    b.HasOne("BangNews.Api.Models.Autor", "Autor")
                        .WithMany("Noticias")
                        .HasForeignKey("AutorID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
