// <auto-generated />
using System;
using BangNews.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BangNews.Api.Migrations
{
    [DbContext(typeof(BangNewsApiContext))]
    [Migration("20190628063240_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BangNews.Api.Models.Autor", b =>
                {
                    b.Property<int>("AutorID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnName("Apellido")
                        .HasMaxLength(50);

                    b.Property<string>("Nombre")
                        .HasColumnName("Nombre")
                        .HasMaxLength(50);

                    b.HasKey("AutorID");

                    b.ToTable("Autor");
                });

            modelBuilder.Entity("BangNews.Api.Models.Nomes", b =>
                {
                    b.Property<int>("NombreID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("NombreID");

                    b.ToTable("Nombres");
                });

            modelBuilder.Entity("BangNews.Api.Models.Noticia", b =>
                {
                    b.Property<int>("NoticiaID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AutorID")
                        .HasColumnName("AutorID")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .HasColumnName("Contenido")
                        .HasMaxLength(2147483647);

                    b.Property<string>("Descripcion")
                        .HasColumnName("Descripcion")
                        .HasMaxLength(100);

                    b.Property<DateTime>("Fecha")
                        .HasColumnName("Fecha")
                        .HasColumnType("Datetime");

                    b.Property<string>("Titulo")
                        .HasColumnName("Titulo")
                        .HasMaxLength(50);

                    b.HasKey("NoticiaID");

                    b.HasIndex("AutorID");

                    b.ToTable("Noticia");
                });

            modelBuilder.Entity("BangNews.Api.Models.Noticia", b =>
                {
                    b.HasOne("BangNews.Api.Models.Autor", "Autor")
                        .WithMany("Noticias")
                        .HasForeignKey("AutorID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
